---
title: "Shocks"
author: "Siddarth Ravikanti"
date: "6/27/2022"
output:
  html_document: default
  pdf_document: default
---

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(viridis)
library(plotly)

load("~/Documents/2022-DSPG-LivDiv-/data/livdivdata.RData")
baseline <- livdiv %>%
slice(1:306,)
```

```{r}
shocks <- baseline %>% select(shk1,shk2,shk3,shk4,shk5,shk6,shk7)
shocks <- data.frame(y=unlist(shocks))
colnames(shocks) <- c('shock_nmb')
shock_labels <- c('None', 'Crop Loss', 'Loss of vegetation', 'Damage caused by saline water encroachment','Forced to move due to Flooding', 'Loss of agricultural land by river erosion','Loss of home by river erosion/cyclone', 'Loss of livestock', 'Loss of business/shop/etc. due to rising water levels', 'Unexpected death or health consequence in Household', 'Other')


ggplot(shocks, aes(shock_nmb)) + geom_histogram() + labs(x = "", y = "Occurances" ,title = "Frequency of Each Shock") + theme(axis.text = element_text(size = 7)) + scale_x_discrete(breaks = c(0,1,2,3,4,5,6,7,8,9,10),labels = str_wrap(shock_labels, width = 25) ,limits = 0:10) + coord_flip()
```


```{r}
shocks2 <- baseline %>% select(village, shk_count) %>% group_by(village) %>% summarize(avg_count = sum(shk_count, na.rm = TRUE)/n())

ggplot(shocks2, aes(village, avg_count, fill = village)) + geom_col() + labs(x = "", y = "Average number of Shocks" ,title = "Average Shocks by Village", fill = "Village") + theme(axis.text.x=element_blank(),axis.ticks.x=element_blank()) + scale_fill_viridis_d() + coord_polar()

```

```{r}
shock_year <- baseline %>% select(shk_2009_count, shk_2010_count, shk_2011_count, shk_2012_count, shk_2013_count, shk_2014_count, shk_2015_count, shk_2016_count, shk_2017_count, shk_2018_count) %>% summarize("2009" = sum(shk_2009_count), "2010" = sum(shk_2010_count), "2011" = sum(shk_2011_count), "2012" = sum(shk_2012_count), "2013" = sum(shk_2013_count), "2014" = sum(shk_2014_count), "2015" = sum(shk_2015_count), "2016" = sum(shk_2016_count),"2017" = sum(shk_2017_count), "2018" = sum(shk_2018_count))

shocks_year_long <- gather(shock_year, year, count, "2009":"2018")

ggplot(shocks_year_long, aes(year, count, fill = year)) + geom_col() + labs(x = "", y = "Count" ,title = "Total Shocks by Year") + theme(axis.ticks.x=element_blank(), legend.position="none") + scale_fill_viridis_d() 

```


```{r}
shocks_2009 <- baseline %>% select(shk_2009_type1, shk_2009_type2, shk_2009_type3, shk_2009_type4, shk_2009_type5, shk_2009_type6)
shock_labels_2009 <- c('None', 'Crop Loss', 'Loss of vegetation', 'Damage caused by saline water encroachment','Forced to move due to Flooding', 'Loss of agricultural land by river erosion','Loss of home by river erosion/cyclone', 'Loss of livestock', 'Loss of business/shop/etc. due to rising water levels', 'Unexpected death or health consequence in Household', 'Other')
shocks_2009 <- data.frame(y=unlist(shocks_2009))
colnames(shocks_2009) <- c('shk')

ggplot(shocks_2009, aes(shk)) + geom_histogram() + labs(x = "", y = "Occurances" ,title = "Frequency of Each Shock in 2009") + theme(axis.text = element_text(size = 7)) + scale_x_discrete(breaks = c(0,1,2,3,4,5,6,7,8,9,10),labels = str_wrap(shock_labels_2009, width = 25) ,limits = 0:10) + coord_flip()

```

```{r}
shocks_cope <- baseline %>% select(village, shk_2009_cope) 

cope_labels <- c("Did not do anything","Unconditional help provided by relatives/friends","Unconditional help provided by local government", "Changed dietary practices involuntarily", "Changed cropping practices", "Household member(s) took on more non-farm employment", "Household member(s) took on more farm wage employment", "Household member(s) migrated", "Relied on savings", "Obtained credit", "Sold durable household assets", "Sold land/building", "Rented out land/building","Distress sales of animal stock", "Sent children to live elsewhere","Reduced expenditures on health and education","Do not know/Do not want to answer")

shocks_cope$shk_2009_cope<-replace(shocks_cope$shk_2009_cope, shocks_cope$shk_2009_cope == 997, 16)

ggplot(shocks_cope, aes(shk_2009_cope, fill = village)) + geom_histogram() + labs(x = "", y = "" ,title = "Type of cope after 2009 shocks", fill = "Village") + scale_fill_viridis_d() + theme(axis.text = element_text(size = 5)) +scale_x_discrete(breaks = c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16), labels = str_wrap(cope_labels, width = 30), limits = 0:20) + coord_flip() 


```

```{r}
shock_relocation <- baseline %>% select(village, shk_2009_reloc_yn)

relocation_labels <- c("No", "Yes, for under a month", "Yes, for over a month")

ggplot(shock_relocation, aes(shk_2009_reloc_yn, fill = village)) + geom_histogram() + labs(x = "", y = "Count" ,title = "Relocation Status after Shock", fill = "Village") + scale_x_discrete(breaks = c(0,1,2), labels = str_wrap(relocation_labels, width = 30), limits = 0:2) + scale_fill_viridis_d()
```


```{r}

shock_relocation_where <- baseline %>% select(village, shk_2009_reloc1)

relocation_where_labels <- c("Within same village","Other village in Sundarbans","Village outside Sundarbans, within West Bengal", "Kolkata", "Other Urban area outside Sundarbans, within West Bengal","Urban area outside West Bengal","Rural area outside West Bengal")

ggplot(shock_relocation_where, aes(shk_2009_reloc1, fill = village)) + geom_histogram() + labs(x = "", y = "Count" ,title = "Relocation Status after Shock", fill = "Village") + scale_x_discrete(breaks = c(1,2,3,4,5,6,7), labels = str_wrap(relocation_where_labels, width = 20), limits = 1:7) + scale_fill_viridis_d() + coord_flip() + theme(plot.title = element_text(hjust = 2))

```

